// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2f-dvIUpp7UmUcGqIogMHMTNNktmpc0A',
    appId: '1:980121603172:web:c947c26945bdcabf022371',
    messagingSenderId: '980121603172',
    projectId: 'lamha-b0e9e',
    authDomain: 'lamha-b0e9e.firebaseapp.com',
    storageBucket: 'lamha-b0e9e.firebasestorage.app',
    measurementId: 'G-J38G9Z5LLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD514oUqqQAMein8c628_657twipPt7ZWo',
    appId: '1:980121603172:android:e0a77de83736de42022371',
    messagingSenderId: '980121603172',
    projectId: 'lamha-b0e9e',
    storageBucket: 'lamha-b0e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgF_ZhIGXahaCcnu6vsSwnqwS2g_nAJc',
    appId: '1:980121603172:ios:75728bcfbe02796e022371',
    messagingSenderId: '980121603172',
    projectId: 'lamha-b0e9e',
    storageBucket: 'lamha-b0e9e.firebasestorage.app',
    iosBundleId: 'com.example.lamha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgF_ZhIGXahaCcnu6vsSwnqwS2g_nAJc',
    appId: '1:980121603172:ios:75728bcfbe02796e022371',
    messagingSenderId: '980121603172',
    projectId: 'lamha-b0e9e',
    storageBucket: 'lamha-b0e9e.firebasestorage.app',
    iosBundleId: 'com.example.lamha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2f-dvIUpp7UmUcGqIogMHMTNNktmpc0A',
    appId: '1:980121603172:web:b7551196feb12ed9022371',
    messagingSenderId: '980121603172',
    projectId: 'lamha-b0e9e',
    authDomain: 'lamha-b0e9e.firebaseapp.com',
    storageBucket: 'lamha-b0e9e.firebasestorage.app',
    measurementId: 'G-EFV5XGHDZM',
  );
}
